# Generated by Django 6.0.8 on 2026-09-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text="e.g. 'naive_lag_24', 'random_forest'.", max_length=100)),
                ('model_type', models.CharField(help_text="'baseline' or 'candidate'.", max_length=20)),
                ('status', models.CharField(choices=[('production', 'Production'), ('rejected', 'Rejected')], max_length=20)),
                ('is_current_production', models.BooleanField(default=False, help_text='True for exactly one row: whatever registry.json currently lists as production.')),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('r2', models.FloatField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text="The promotion-gate reason string, e.g. from registry.py's evaluate_promotion().")),
                ('evaluated_at', models.DateTimeField(help_text='When this decision was recorded in registry.json.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
