# Generated by Django 6.0.8 on 2026-09-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='The target hour this forecast is for.')),
                ('predicted_load_mw', models.FloatField(help_text='The forecasted load, in MW.')),
                ('actual_load_mw', models.FloatField(blank=True, help_text='The real load once known; null until the target hour has passed.', null=True)),
                ('model_type', models.CharField(help_text="'baseline' or 'candidate', matching ProductionModel.info().", max_length=20)),
                ('model_name', models.CharField(help_text="e.g. 'naive_lag_24' or 'random_forest'.", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='forecasts_f_timesta_d08a72_idx')],
            },
        ),
    ]
