# Generated by Django 6.0.8 on 2026-09-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(help_text='When this check was run.')),
                ('drift_detected', models.BooleanField()),
                ('drifted_column_share', models.FloatField(help_text='e.g. 0.737 for 73.7% of features drifted.')),
                ('drifted_column_count', models.IntegerField()),
                ('n_columns', models.IntegerField()),
                ('performance_degraded', models.BooleanField()),
                ('recent_mae', models.FloatField(blank=True, null=True)),
                ('reference_mae', models.FloatField(blank=True, null=True)),
                ('relative_increase', models.FloatField(blank=True, help_text='(recent_mae - reference_mae) / reference_mae.', null=True)),
                ('retrain_recommended', models.BooleanField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
